PUT http://localhost:3001/api/posts/62caccebe21b2172db8ad385 HTTP/1.1
content-type: application/json

{
    "userId": "id3",
    "description": "hubie's first post mnumber 2",
    "image": "hellosir212.jpg"
}

