PUT http://localhost:3001/api/users/62c9998e6559d5bf251e67a8 HTTP/1.1
content-type: application/json

{
    "description": "math god",
    "userId": "62c9998e6559d5bf251e67a8",
    "password": "evaniscool#discordmod123"
}

