POST http://localhost:3001/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "Dubniel", 
    "email": "dgfan@gmail.com", 
    "password": "evaniscool#discordmod123", 
    "location": "Ontario, Canada", 
    "description": "This is dubstep daniel dubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep danieldubstep daniel", 
    "socialLinks": ["Soundcloud: soundcloud.com/heir"], 
    "coverPic": "cover.png"
}