export const Users = [ 
    {
      id:1,
      profilePicture: "users/mark.jfif",
      username: "MetalMark",
    },
    {
      id:2,
      profilePicture: "users/hubert.jpg",
      username: "HiphopHubert",
    },
    {
      id:3,
      profilePicture: "users/matthew.jfif",
      username: "ModalMatthew",
    },
    {
      id:4,
      profilePicture: "users/evan.jpg",
      username: "EdmEvan",
    },
    {
      id:5,
      profilePicture: "users/larry.jpg",
      username: "LofiLarry",
    },
  ];
  
  export const Posts = [
    { //metalmark
      id: 1,
      title: "How do I tune this guitar????????",
      description: "My guitar is so shit dude this is insane i cant believe how shit my guitar is. why the fuck does it always fuck up bruh this is so cringe cringe cringe cringe cringe cringe cringe cringe",
      image: "posts/guitar.jfif",
      date: "5 mins ago",
      userId: 1,
      likes: 5,
      comments: 9,
    },
    { //hiphophubert
      id: 2,
      title: "HEY GUYS check out my setup!!!!!!!!!! (ignore the stains on my bed)",
      image: "posts/abletonSetup.jpg",
      date: "15 mins ago",
      userId: 2,
      likes: 2,
      comments: 1,
    },
    { //modal matthew
      id: 3,
      title: "Have you heard of this underground artist Aevyan?",
      description: "posts/aevyan.jpg",
      image:"aevyan.jpg",
      date: "1 hour ago",
      userId: 3,
      likes: 61,
      comments: 2,
    },
    { //edmevan
      id: 4,
      title: "What do you guys think of the new porter robinson album?",
      image: "posts/nurture.jfif",
      date: "4 hours ago",
      userId: 4,
      likes: 7,
      comments: 3,
    },
    { //lofilarry
      id: 5,
      title: "How tf is this sound created?",
      description: "I've recently been listening to DAOKO × Kenshi Yonezu - Fireworks. Does anyone know what libraries are used for the string sections of the chorus? I've tried session strings but they sound kind of robotic and too harsh ",
      image: "posts/fireworks.jfif",
      date: "2 days ago",
      userId: 5,
      likes: 52,
      comments: 3,
    },
    { //metalmark
      id: 6,
      title: "20 KONTAKT INSTANCES OPEN, GOOD LUCK CPU !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
      image: "posts/kontakt.jpeg",
      date: "3 days ago",
      userId: 1,
      likes: 15,
      comments: 1,
    },
    { //modalmatthew
      id: 7,
      title: "Meaningless post title",
      description: "Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. Change the world by being yourself. ",
      image: "posts/profilePic.jpg",
      date: "5 days ago",
      userId: 3,
      likes: 11,
      comments: 2,
    },
  ];